In [ ]:
[动态规划1](https://www.bilibili.com/video/BV12W411v7rd)
[动态规划2](https://www.bilibili.com/video/BV1AB4y1w7eT/)

In [2]:
# 1. 在一个数组arr中，找出一组不相邻的数字，使得最后的和最大。

import numpy as np
arr = [1, 2, 4, 1, 7, 8, 3]

def rec_opt(arr, i):
    if i == 0:
        return arr[0]
    elif i == 1:
        return max(arr[0], arr[1])
    else:
        A = rec_opt(arr, i-2) + arr[i]
        B = rec_opt(arr, i-1)
        return max(A,B)

def dp_opt(arr,i):
    opt = np.zeros(len(arr), dtype = int)
    opt[0] = arr[0]
    opt[1] = max(arr[0],arr[1])
    for i in range(2, len(arr)):
        A = opt[i-2] + arr[i]
        B = opt[i-1]
        opt[i] = max(A,B)
    return opt[len(arr) -1]
    
print(rec_opt(arr,6))
dp_opt(arr,6)


15


15

In [3]:
# 2. 给定一个正整数s, 判断一个数组arr中，是否有一组数字加起来等于s。
arr = [3, 34, 4, 12, 5, 2]
def rec_subset(arr, i, s):
    if s == 0:
        return True
    elif i == 0:
        return arr[0] == s
    elif arr[i] > s:
        return rec_subset(arr, i-1, s)
    else:
        A = rec_subset(arr, i-1, s-arr[i])
        B = rec_subset(arr, i-1, s)
        return A or B
print(rec_subset(arr, len(arr)-1, 9))
print(rec_subset(arr, len(arr)-1, 10))
print(rec_subset(arr, len(arr)-1, 11))
print(rec_subset(arr, len(arr)-1, 12))
print(rec_subset(arr, len(arr)-1, 13))

True
True
True
True
False


In [5]:
#  案例！！
arr = [3, 34, 4, 12, 5, 2]
def dp_subset(arr, S):
    subset = np.zeros((len(arr), S+1),dtype=bool)
    subset[:,0] = True
    subset[0,:] = False
    subset[0,arr[0]] = True
    for i in range(1,len(arr)):
        for s in range(1, S+1):
            if arr[i] > s:
                subset[i,s] = subset[i-1,s]
            else:
                A = subset[i-1, s-arr[i]]
                B = subset[i-1, s]
                subset[i,s] = A or B
    r, c = subset.shape
    return subset[r-1, c-1]

print(dp_subset(arr,  9))
print(dp_subset(arr,  10))
print(dp_subset(arr,  11))
print(dp_subset(arr,  12))
print(dp_subset(arr,  13))

True
True
True
True
False


In [11]:
%%timeit
def L(num, i):

    if i == len(nums) - 1: # last number
        return 1
    
    max_len = 1
    for j in range(i+1, len(nums)):
        if num[j] > num[i]:
            max_len = max(max_len, L(num, j) +1)
    return max_len

def len_of_LIS(nums):
    max_len = 0
    for i in range(len(nums)):
        max_len = max(max_len, L(nums, i))
    return max_len
    # return max(L(nums, i) for i in range(len(nums)))

nums = [1,5,2,4,3,1,4,56,78,43,52,51,64,23,52,34,56,123,43,123,12,35,36,54,98,13,156,178,98,65,45,12,64,48,122,1,135]
print(len_of_LIS(nums))

12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
45.3 ms ± 1.28 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [13]:
%%timeit
# 大量的重复计算

memo = {}
def L(num, i):

    if i in memo:
        return memo[i]

    if i == len(nums) - 1: # last number
        return 1
    
    max_len = 1
    for j in range(i+1, len(nums)):
        if num[j] > num[i]:
            max_len = max(max_len, L(num, j) +1)

    memo[i] = max_len
    return max_len

def len_of_LIS(nums):
    max_len = 0
    for i in range(len(nums)):
        max_len = max(max_len, L(nums, i))
    return max_len
    # return max(L(nums, i) for i in range(len(nums)))

nums = [1,5,2,4,3,1,4,56,78,43,52,51,64,23,52,34,56,123,43,123,12,35,36,54,98,13,156,178,98,65,45,12,64,48,122,1,135]
print(len_of_LIS(nums))

12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
1

In [21]:
def length_of_LIS(nums):
    n = len(nums)
    L = [1] * n

    for i in range(n-1,-1,-1):
        for j in range(i+1,n):
            if nums[j] > nums[i]:
                L[i] = max(L[i],L[j] +1 )
    return max(L)
nums = [1,5,2,4,3,1,4,56,78,43,52,51,64,23,52,34,56,123,43,123,12,35,36,54,98,13,156,178,98,65,45,12,64,48,122,1,135]
print(length_of_LIS(nums))

12


In [44]:
import numpy as np
arr = [3, 3]
def dp_ge(arr):
    if arr[0] < 0 or arr[1] < 0:
        return 0
    
    subset = np.zeros((arr[0], arr[1]),dtype=int)
    subset[:,0] = 1
    subset[0,:] = 1
    # for i in range(arr[0]):
    #     subset[i][0] = 1
    # for j in range(arr[1]):
    #     subset[0][j] = 1
    for i in range(1,arr[0]):
        for j in range(1,arr[1]):
            subset[i][j] = subset[i-1][j] + subset[i][j-1]
    print(subset)
    return subset[arr[0]-1,arr[1]-1]
    
dp_ge(arr)

[[1 1 1]
 [1 2 3]
 [1 3 6]]


6

In [28]:
inp = 'woh era uoy ? I ma enif.'
a = [' ',',','.','?']
l = []
inp.split(" |,|?|.")
# for i in inp:
#     if i not in a:
#         l.append(i[::-1])
# print(l)


['woh era uoy ? I ma enif.']

In [42]:
inp = 'yM eman si boB.'
l = inp.split(" ")
print(l)
l1 = []
for i in l:
    if i[-1] not in ('?',',',"."):
        l1.append(i[::-1])
    elif len(i) == 1:
        l1.append(i)
    else:
        tem = i[len(i)-2::-1] + i[-1]
        l1.append(tem)
outp = " ".join(l1) # str.join(iterable) str是分隔符
print(outp)

['yM', 'eman', 'si', 'boB.']
My>name>is>Bob.
